### ISSUE TITLE
Screenshot size

### ISSUE THREAD

**Issue by agoalofalife** [ptkdev/instagram-bot.js#11]
In dependencies there [puppeteer](https://github.com/GoogleChrome/puppeteer)
I was faced with the problem of crash of browser chromium.
In issues [puppeteer](https://github.com/GoogleChrome/puppeteer/issues/2255) I found a hint
but the screenshot size not set 
```js
// bot.js
    async screenshot(func, name) {
        try{
            await this.bot.screenshot({ path: './logs/screenshot/' + this.config.instagram_username + '_' + func + '_' + name + '.jpg' });
        } catch (err) {
            this.logger("[WARNING]", "screenshot", "error "+ err);
        }
    }
```
I propose to take the size of the screenshot for example of configuration and pass object the third parameter
example:
```js
// bot.js
    async screenshot(func, name, configObject) {
        try{
         let param = Object.assign({ path: './logs/screenshot/' + this.config.instagram_username + '_' + func + '_' + name + '.jpg' }, configObject);
            await this.bot.screenshot(param);
        } catch (err) {
            this.logger("[WARNING]", "screenshot", "error "+ err);
        }
    }
```
And we can pass these parameters
 
```js
clip:{
 width:100,
height:100
        } 
```
**Оption 2**

in the function itself to specify additional arguments from the configuration

```js
const config = require(__dirname + '/config');

    async screenshot(func, name) {
        try{
   let param = Object.assign({ path: './logs/screenshot/' + this.config.instagram_username + '_' + func + '_' + name + '.jpg' }, config.screenshot);
            await this.bot.screenshot(param);
        } catch (err) {
            this.logger("[WARNING]", "screenshot", "error "+ err);
        }
    }
```

**Comment by agoalofalife** [comment]
I can send PR

**Comment by ptkdev** [comment]
Hi!
This config is require in puppeeteer 1.2 fast fix is downgrade to 1.0.0

Option 2 is better for me. If you send pull request i merge it.

**Comment by agoalofalife** [comment]
Ok, I need a little time

**Comment by ptkdev** [comment]
No problem, if you don't have time i fix this tomorrow.
in config.js.tpl call param: `config.screenshot_size = clip:{width:100,height:100 } `

**Comment by agoalofalife** [comment]
I was faced with another problem
if we define the width and height, it is also necessary `x` and `y`

**Comment by ptkdev** [comment]
Ok, no problem If necessary add another param `screenshot_position` or if possible add `x` and `y` in clip. 

Default screenshot size `800x600`

**Comment by agoalofalife** [comment]
The problem is that when adding coordinates the browser continues to crash
Probably I hurried
Browser not crash , because `puppeteer` not work
Xmm....
I'll keep looking)

**Comment by ptkdev** [comment]
Tonight i test bot with puppeteer, wait for me news :)

**Comment by agoalofalife** [comment]
ok, it is interesting that I had no problems on another computer
Without problem `Mac Air 13 4gb`
With problem `Mac Pro 15 8gb`

**Comment by ptkdev** [comment]
Solution is install `google-chrome >= v61` on your mac and edit bot.js

- edit `bot.js` in root at line 58 (release v0.6.1)
- add executablePath in puppeteer.launch:
- `const browser = await puppeteer.launch({executablePath: '/path/to/Chrome',headless: config.chrome_headless, args: config.chrome_options});`

This happen when puppeteer don't support arch of machine/os

**Comment by agoalofalife** [comment]
you're just cool!
thank you!
Yes, only works Chrome(
I think we should add to the configuration parameter `executablePath`
for such cases))

**Comment by ptkdev** [comment]
Yep, you are right. I add screenshot size and executablePath parameters in next release :)
