### ISSUE TITLE
[ITA] Raspberry PI 3B - Support

### ISSUE THREAD

**Issue by matteocef** [ptkdev/instagram-bot.js#2]
Sento che ci sono vicino, ma manca qualcosa. Ho letto tutti i cazzo di troubleshooting, ma non capisco cosa è che non gli fa lanciare Chromium. 

Sto su Raspberry pi 3B con Raspbian.
```
[pi@raspberrypi:~/instagram-bot.js $ node bot.js 
(node:3241) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
/home/pi/instagram-bot.js/node_modules/puppeteer/.local-chromium/linux-526987/chrome-linux/chrome: 3: /home/pi/instagram-bot.js/node_modules/puppeteer/.local-chromium/linux-526987/chrome-linux/chrome: Syntax error: ")" unexpected


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

(node:3241) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
>

**Comment by ptkdev** [comment]
Versione di node? Purtroppo Raspberry pi 3B non è tra i device supportati.

Ricorda di abilitare `chrome_headless` nel config quando usi un device senza monitor ma da riga di comando

**Comment by matteocef** [comment]
ah, ok :( ti avevo chiesto su facebook e per quello sono andato diretto. Ora vedo la versione di node. L'headless dovrebbe essere su true, e dovrei avere installato chromium-bsu già, perchè quando metto chromium mi dice che quello disponibile è bsu

**Comment by ptkdev** [comment]
`bot.js` riga 56
`const browser = await puppeteer.launch({executablePath: '/path/to/Chrome',headless: config.chrome_headless, args: config.chrome_options});`

Prima della voce headless aggiungi il path di chromium-bsu che dovrebbe essere `/usr/bin/chromium` così viene usato il chromium compilato per Raspberry pi 3B.

**Comment by matteocef** [comment]
Appena torno a casa riprovo. Prima di uscire ho cercato la path di chromium-bsu (che sta su /usr/games/ ...boh) e ho trovato la path di chromium-browser,proverò entrambi!

**Comment by ptkdev** [comment]
Ricorda che la minima versione per il bot di node è 7.6 e chromium è la v63

**Comment by matteocef** [comment]
La versione di note supera la 7.6, ma chromium su rasp si ferma alla v60, appena controllato :(

**Comment by matteocef** [comment]
Ho riprovato con Chromium-bsu e: 
```
pi@raspberrypi:~/instagram-bot.js $ node bot.js
(node:2105) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!

--------------------------------------------------
Chromium B.S.U. options
--------------------------------------------------
   -f/--fullscreen     : run in fullscreen mode
   -w/--window         : run in windowed mode
   -v/--vidmode <mode> : mode 0 =  512 x  384
                       :      1 =  640 x  480
                       :      2 =  800 x  600
                       :      3 = 1024 x  768
                       :      4 = 1280 x  960
  -na/--noaudio        : do not initialize audio
  -nb/--noblend        : disable blending (OpenGL)
  -nt/--notexborder    : do not set tex border color (OpenGL)
  -V/--version         : show version information
--------------------------------------------------



TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

(node:2105) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by matteocef** [comment]
Ok. 
Su RB3 non va. Ma ho letto ora il changelog, e visto che è multiplatform. Messo sul mac in 1 minuto. e va. <3 ora devo provare solo a farlo andare in headless.

**Comment by ptkdev** [comment]
Aspettiamo la >= v63 di chromium su RB3

**Comment by julianxhokaxhiu** [comment]
Oppure puoi installare Arch Linux ARM e puoi usare sempre l'ultimissima versione di Chromium :)

@ptkdev magari se stasera ho tempo ti faccio un container da usare su Raspi. Docker su RPi2/3 va che è una figata :D

**Comment by ptkdev** [comment]
Ho controllato e su Arch Linux ARM c'è Chromium v64, quindi dovrebbe funzionare. Nel weekend faccio un test.

**Comment by ptkdev** [comment]
SOLVED:
### 1. Install chromium v60
- `apt-get install chromium-browser`

### 2. Update chromium v60 to v64
```
wget http://launchpadlibrarian.net/252010249/libfontconfig1_2.11.94-0ubuntu1_armhf.deb
wget https://launchpad.net/~chromium-team/+archive/ubuntu/stable/+build/14349678/+files/chromium-codecs-ffmpeg_64.0.3282.167-0ubuntu0.17.10.1_armhf.deb
wget https://launchpad.net/~chromium-team/+archive/ubuntu/stable/+build/14349678/+files/chromium-browser_64.0.3282.167-0ubuntu0.17.10.1_armhf.deb

sudo dpkg -i libfontconfig1_2.11.94-0ubuntu1_armhf.deb
sudo dpkg -i chromium-codecs-ffmpeg_64.0.3282.167-0ubuntu0.17.10.1_armhf.deb
sudp dpkg -i chromium-browser_64.0.3282.167-0ubuntu0.17.10.1_armhf.deb
```
### 3. Use raspbian chromium, not the node_modules version
- Edit `bot.js` at line ~59 and add chrome path:
- `const browser = await puppeteer.launch({executablePath: '/usr/bin/chromium-browser', headless: config.chrome_headless, args: config.chrome_options});`

### 4. If you have problem with libc dependieces you need update raspbian to testing:
- Edit `/etc/apt/source.list` and change `stretch` to `testing`
- Run `sudo apt-get update && apt-get dist-upgrade`
