### ISSUE TITLE
Like doesn't work if the language is not in English

### ISSUE THREAD

**Issue by thebatclaudio** [ptkdev/instagram-bot.js#3]
Like doesn't work if the language of Instagram is not in English, because in modules/likemode_classic.js:134 there is this condition: html_text=="Like"

**Comment by ptkdev** [comment]
`npm install` install english chromium (without locale languages), why os you use?

**Comment by ptkdev** [comment]
`html_text == "Like"` is duplicate (useless) check, i remove it on v0.5.2

`heart = await this.bot.$('.coreSpriteHeartOpen');` check if heart of instagram is open, work without `html_text == "Like"`
