### ISSUE TITLE
Problem starting node bot.js

### ISSUE THREAD

**Issue by maxifried** [ptkdev/instagram-bot.js#5]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.5.2
- **Operating System:** Windows 7
- **Browser:** Google Chrome 64

### Expected Behavior

 I just want to start the bot but im having some issues.

### Actual Behavior

Starting with node bot.js

![nodebotjs](https://user-images.githubusercontent.com/28242475/35946498-c138602c-0c42-11e8-9810-d12b7bdbfd1e.jpg)

Starting with npm run start
![npmrunstart](https://user-images.githubusercontent.com/28242475/35946511-d091cfb8-0c42-11e8-8619-30a3c7970305.jpg)

**Comment by ptkdev** [comment]
Error is on async function. async work with node >= 7.6 

You system have node 6.X

**Comment by maxifried** [comment]
@ptkdev  so i have to update my node?

**Comment by ptkdev** [comment]
Solution is update node to v8.9 actually LTS

**Comment by ptkdev** [comment]
Thanks, remember to add :star: to project if solution work :+1:
