### ISSUE TITLE
bot_fastlike_min 2 times

### ISSUE THREAD

**Issue by matteocef** [ptkdev/instagram-bot.js#6]
I noticed that on the config.js.tpl is declared the bot_fastlike_min two times, instead of one bot_fastlike_min and one bot_fastlike_max. The bot still works in the realistic mode, but i guess it take just one value and the other is random.

**Comment by ptkdev** [comment]
Hi!
Thanks, that misprint are fixed in v0.6.1

**Comment by ptkdev** [comment]
Release v0.6.1 available.

**Comment by ptkdev** [comment]
Release v0.6.1 available.
